version: '3.7'
services:
  web:
    image: nginx:1.21.4
    ports:
      - '80:80'
    depends_on:
      - app
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www/html
    container_name: "nginx_ec_system"
    platform: linux/x86_64
    tty: true

  app:
    build: ./
    volumes:
      - ./app:/var/www/html
    working_dir: "/var/www/html"
    container_name: "php_ec_system"
    platform: linux/x86_64
    tty: true

  nodejs:
    image: node:16.13.0
    volumes:
      - ./app:/usr/app
    ports:
      - "3000:3000"
    working_dir: "/usr/app"
    container_name: "nodejs_ec_system"
    platform: linux/x86_64
    tty: true

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    container_name: "mysql_ec_system"
    platform: linux/x86_64
    tty: true